export type ListingType = "sale" | "rent";
export type PropertyCategory = "house" | "apartment" | "land" | "commercial" | "other";
export type UgandaRegion = "central" | "eastern" | "northern" | "western";
export type ListingStatus = "available" | "under_offer" | "sold" | "rented";
export type RentPeriod = "day" | "week" | "month" | "year";
export type FurnishingStatus = "furnished" | "semi_furnished" | "unfurnished";
export type ContactPreference = "message" | "phone" | "whatsapp" | "email";

export type PropertyRow = {
  id: string;
  owner_id: string;
  title: string;
  description: string | null;
  listing_type: ListingType;
  property_category: PropertyCategory;
  price: number;
  currency: string;
  price_negotiable: boolean;
  rent_period: RentPeriod | null;
  listing_status: ListingStatus;
  region: UgandaRegion;
  city: string;
  district: string | null;
  address_line: string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  parking_spaces: number | null;
  furnishing: FurnishingStatus | null;
  land_size_sqm: number | null;
  built_size_sqm: number | null;
  image_urls: string[] | null;
  video_url: string | null;
  virtual_tour_url: string | null;
  amenities: string[] | null;
  seller_name: string | null;
  seller_phone: string | null;
  seller_whatsapp: string | null;
  seller_email: string | null;
  contact_preference: ContactPreference;
  available_from: string | null;
  is_published: boolean;
  created_at: string;
  updated_at: string;
};
